### PR TITLE
Prepare for supporting multiple installed package managers

### PR DESCRIPTION
**Pull request by LeWolfYT**

### CODE REVIEW

**Review by sidgames5 — COMMENTED** [review]
I honestly see no point in this because the existing code already provides the first package manager that the system has

**Comment by LeWolfYT** [comment]
the point is that the user could choose which package manager they want to use. the purpose is choice.

**Comment by sidgames5** [comment]
That would be part of the config commands. This will be coming in a future update.

**Comment by LeWolfYT** [comment]
we should still merge this because i modified the scanner

**Pull request merged**
